# Generated by Django 3.2.5 on 2021-08-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_respuesta', models.IntegerField(unique=True)),
                ('pregunta', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesta',
            fields=[
                ('id_respuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=20)),
                ('es_la_correta', models.BooleanField()),
            ],
        ),
    ]
