# Generated by Django 3.2.5 on 2021-08-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0011_alter_pregunta_id_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repuesta',
        ),
    ]
