# Generated by Django 3.2.5 on 2021-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0012_delete_repuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_respuesta', models.IntegerField()),
                ('respuesta', models.CharField(max_length=50)),
                ('es_correta', models.BooleanField()),
            ],
        ),
    ]
